import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import { ToastProvider } from "@/components/ui/toast/toast-provider";


export const metadata: Metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
